---
apiVersion: v1
kind: Secret
metadata:
  name: psql-secrets
type: Opaque
data:
  ROOT_PASSWORD: cm9vdA==
---
#kubectl get secret
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-data-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment # this is url 'jdbc:mysql://mysql-deployment:3306/mydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'
  labels:
    app: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              subPath: "psql"
              name: psql-data
          env:
            - name: POSTGRES_USER
              value: 'root'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secrets
                  key: ROOT_PASSWORD
            - name: POSTGRES_DB
              value: 'mydb'
      volumes:
        - name: psql-data
          persistentVolumeClaim:
            claimName: psql-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: psql
  labels:
    name: psql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: psql
  type: LoadBalancer
