apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stack-pop
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: stack-pop
    spec:
      containers:
        - name: stack-pop
          image: 'himanshu007/stack-pop:main'
          ports:
          - containerPort: 8078
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stack-pop
  labels:
    name: stack-pop
spec:
  ports:
    - port: 8078
      targetPort: 8078
      protocol: TCP
  selector:
    app: stack-pop
  type: LoadBalancer
